language: python
cache: pip
os:
  - linux
python:
  - "2.7"
# command to install dependencies
install:
  - pip install PySide
  - pip install Qt.py
# command to run tests
script: python mighty_test.py